name: Treebreaker
main: main.java.treebreaker.plugin.Main
version: 1.16.4.1.4
author: Daniel Allen
api-version: 1.16
load: STARTUP
commands:
    treebreaker:
        description: Checks for updates
    deathLocation:
        description: Displays your last death location and the time remaining before your items expire
        usage: /deathLocation
        aliases: [dl]
    setProperty:
        description: Sets a property in the Treebreaker plugin.
        usage: /setProperty [property]
        aliases: [sp]
    track:
        description: Does glitchy stuff
    mobCount:
        description: Counts how many of a mob are in the game
    EZEnchant:
        description: Provides a convienient enchantment system
    allEnchant:
        description: Applies all enchantments to an item at once